version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/swappy-backend
    overwrite: true
  - source: scripts/
    destination: /home/ec2-user/swappy-backend/scripts
    overwrite: true

hooks:
  BeforeInstall:
    - location: scripts/cleanup.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/post_deploy.sh
      timeout: 300
      runas: ec2-user
